require_relative "./config.rb"
require_relative "./import-bg.rb"
require_relative "./import-char.rb"
require_relative "./import-item.rb"
require_relative "./import-map.rb"
require_relative "./import-stated.rb"
require_relative "./import-tts-objs.rb"
puts "all done"
