on:
  push:
    branches:
    - master

jobs:
  build:
    name: update catalogue.md to match catalogue.csv
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@master

      - name: read catalogue.csv
        id: csv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./catalogue.csv

      - name: generate md
        uses: petems/csv-to-md-table-action@master
        id: csv-table-output
        with:
          csvinput: ${{ steps.csv.outputs.content }}
          
      - name: write to catalogue.md
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ./catalogue.md
          write-mode: overwrite
          contents: |
            ${{steps.csv-table-output.outputs.markdown-table}}
            
      - name: commit and push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'updated by github actions'
